(defun fm2val (fm)
  (cond ((numberp fm) fm)
        ((null (cdr fm)) (fm2val (car fm)))
        ((eql (cadr fm) '+)
          (+ (fm2val (car fm)) (fm2val (cddr fm))))
        ((eql (cadr fm) '-)
            (+ (fm2val (car fm))
               (fm2val (cons (- (fm2val (caddr fm)))
                                        (cdddr fm)))))
        (t (fm2val (cons (eval (list (cadr fm)
                                     (fm2val (car fm))
                                     (fm2val (caddr fm))))
                         (cdddr fm))))))

(print (fm2val '(1 + 3 * 4 - 3)))
